/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Human: typeof import('./components/assets/human.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./components/tools/ThemeSwitch.vue')['default']
    TimelineLaye: typeof import('./components/editor/TimelineLaye.vue')['default']
    TimelineLayer: typeof import('./components/editor/TimelineLayer.vue')['default']
    TimelineLayerControl: typeof import('./components/editor/TimelineLayerControl.vue')['default']
    TimelineLayerItem: typeof import('./components/editor/TimelineLayerItem.vue')['default']
    TimelineMedia: typeof import('./components/editor/TimelineMedia.vue')['default']
    TimelineScale: typeof import('./components/editor/TimelineScale.vue')['default']
    TimelineTool: typeof import('./components/editor/TimelineTool.vue')['default']
    ViewportWrapper: typeof import('./components/window/ViewportWrapper.vue')['default']
  }
}
