/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/timeline/track/TimelineRuler copy 2.vue')['default']
    Assets: typeof import('./components/assets/index.vue')['default']
    AssetsPanel: typeof import('./components/AssetsPanel.vue')['default']
    copy: typeof import('./components/timeline/track/TimelineRuler copy.vue')['default']
    DraggableContainer: typeof import('./components/editor/DraggableContainer.vue')['default']
    DraggableSourceContainer: typeof import('./components/DraggableSourceContainer.vue')['default']
    DraggableSourceWizard: typeof import('./components/DraggableSourceWizard.vue')['default']
    DraggableTargetContainer: typeof import('./components/DraggableTargetContainer.vue')['default']
    DraggableWizard: typeof import('./components/editor/DraggableWizard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    History: typeof import('./components/assets/history.vue')['default']
    Human: typeof import('./components/assets/human.vue')['default']
    Image: typeof import('./components/assets/image.vue')['default']
    Movie: typeof import('./components/assets/movie.vue')['default']
    MovieFx: typeof import('./components/assets/movie-fx.vue')['default']
    PreviewArea: typeof import('./components/PreviewArea.vue')['default']
    PropertiesPanel: typeof import('./components/PropertiesPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subtitle: typeof import('./components/assets/subtitle.vue')['default']
    Text: typeof import('./components/assets/text.vue')['default']
    ThemeSwitch: typeof import('./components/tools/ThemeSwitch.vue')['default']
    Timeline: typeof import('./components/Timeline.vue')['default']
    TimelineClip: typeof import('./components/timeline/track/TimelineClip.vue')['default']
    TimelineControls: typeof import('./components/timeline/TimelineControls.vue')['default']
    TimelineLaye: typeof import('./components/editor/TimelineLaye.vue')['default']
    TimelineLayer: typeof import('./components/editor/TimelineLayer.vue')['default']
    TimelineLayerControl: typeof import('./components/timeline/track/TimelineLayerControl.vue')['default']
    TimelineLayerItem: typeof import('./components/timeline/track/TimelineLayerItem.vue')['default']
    TimelineLayerList: typeof import('./components/editor/TimelineLayerList.vue')['default']
    TimelineMedia: typeof import('./components/editor/TimelineMedia.vue')['default']
    TimelineRuler: typeof import('./components/timeline/track/TimelineRuler.vue')['default']
    TimelineScale: typeof import('./components/timeline/TimelineScale.vue')['default']
    TimelineTool: typeof import('./components/timeline/TimelineTool.vue')['default']
    TimelineTrack: typeof import('./components/timeline/track/TimelineTrack.vue')['default']
    TimelineZoomLevel: typeof import('./components/timeline/TimelineZoomLevel.vue')['default']
    ViewportControl: typeof import('./components/ViewportControl.vue')['default']
    ViewportWrapper: typeof import('./components/window/ViewportWrapper.vue')['default']
  }
}
