/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/demo/draggable': RouteRecordInfo<'/demo/draggable', '/demo/draggable', Record<never, never>, Record<never, never>>,
    '/demo/ffmpeg.wasm.demo': RouteRecordInfo<'/demo/ffmpeg.wasm.demo', '/demo/ffmpeg/wasm/demo', Record<never, never>, Record<never, never>>,
    '/demo/timeline.media': RouteRecordInfo<'/demo/timeline.media', '/demo/timeline/media', Record<never, never>, Record<never, never>>,
    '/editor': RouteRecordInfo<'/editor', '/editor', Record<never, never>, Record<never, never>>,
    '/editor/': RouteRecordInfo<'/editor/', '/editor', Record<never, never>, Record<never, never>>,
    '/editor/assets/': RouteRecordInfo<'/editor/assets/', '/editor/assets', Record<never, never>, Record<never, never>>,
    '/editor/assets/history': RouteRecordInfo<'/editor/assets/history', '/editor/assets/history', Record<never, never>, Record<never, never>>,
    '/editor/assets/human': RouteRecordInfo<'/editor/assets/human', '/editor/assets/human', Record<never, never>, Record<never, never>>,
    '/editor/assets/image': RouteRecordInfo<'/editor/assets/image', '/editor/assets/image', Record<never, never>, Record<never, never>>,
    '/editor/assets/movie': RouteRecordInfo<'/editor/assets/movie', '/editor/assets/movie', Record<never, never>, Record<never, never>>,
    '/editor/assets/movie-fx': RouteRecordInfo<'/editor/assets/movie-fx', '/editor/assets/movie-fx', Record<never, never>, Record<never, never>>,
    '/editor/assets/subtitle': RouteRecordInfo<'/editor/assets/subtitle', '/editor/assets/subtitle', Record<never, never>, Record<never, never>>,
    '/editor/assets/text': RouteRecordInfo<'/editor/assets/text', '/editor/assets/text', Record<never, never>, Record<never, never>>,
    '/editor/preview/': RouteRecordInfo<'/editor/preview/', '/editor/preview', Record<never, never>, Record<never, never>>,
    '/editor/settings/': RouteRecordInfo<'/editor/settings/', '/editor/settings', Record<never, never>, Record<never, never>>,
    '/editor/timeline/': RouteRecordInfo<'/editor/timeline/', '/editor/timeline', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
